\c kampi

INSERT INTO drzave (drzava_id, naziv) VALUES (1, 'Hrvaška');
INSERT INTO drzave (drzava_id, naziv) VALUES (2, 'Srbija');
INSERT INTO drzave (drzava_id, naziv) VALUES (3, 'Slovenija');
INSERT INTO drzave (drzava_id, naziv) VALUES (4, 'Črna Gora');
INSERT INTO drzave (drzava_id, naziv) VALUES (5, 'BiH');

INSERT INTO regije (regija_id, naziv, drzava) VALUES (2, 'Dalmacija', 1);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (1, 'Kvarner', 1);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (3, 'Istra', 1);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (4, 'Primorska', 3);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (6, 'Gorenjska', 3);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (7, 'Goriška', 3);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (8, 'Mostar', 5);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (9, 'Budva', 4);
INSERT INTO regije (regija_id, naziv, drzava) VALUES (5, 'Južna Srbija', 2);

INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (3, 'Kamp Tiha Šilo', 'Kamp Tiha Šilo se nahaja na vzhodni strani otoka Krk, na samotnem polotoku v kraju Šilo do katerega lahko pridete po cesti preko kraja Malinska ali pa po novi lokalni cesti Omišalj - Čižići - Klimno - Šilo.', '051897852', 'Konjska bb, 51515 Šilo', 'Šilo', '45.145827', '14.662310', 1);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (7, 'Kamp Lucija', 'Kamp Lucija je urejen na zelenem polotoku Seča. Kamp ima urejenih okoli 550 parcel in lahko sprejme do 1.000 gostov. Od centra Portoroža, največjega slovenskega obmorskega letovišča, je kamp oddaljen slab kilometer.', '041631789', 'Seča 204, 6320 Portorož', 'Portorož', '45.502124', '13.600714', 4);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (8, 'Kamp Fiesa', 'Kamp Fiesa leži v zelenem, mirnem zalivu Fiesa, ki je od Portoroža oddaljen le 3 km, in je znan tudi po dveh sladkovodnih jezercih. Kamp je od morja oddaljen le 100 m, njegova kapaciteta pa je 112 prikolic, 35 šotorišč ter manjši prostor za avtodome.', '031390561', 'Fiesa 57b, 6330 Piran', 'Piran', '45.524112', '13.580028', 4);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (9, 'Kamp Bled', 'Kamp Bled obratuje že vse od leta 1950. Leži na zahodni strani Blejskega jezera, od katerega je oddaljen cca 150 metrov. Prednosti kampa sta idilična lega v lepem naravnem okolju v neposredni bližini jezera in kratka oddaljenost od centra Bleda (2km). Gre za miren kamp, kjer uživajo ljubitelji lepe narave, pohodništva in kolesarjenja.', '051456911', 'Kidričeva 10 C, 4260 Bled', 'Bled', '46.361734', '14.080963', 6);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (10, 'Kamp Nadiža', 'Kamp Nadiža leži v skrivnostnem Breginjskem kotu leži na dnu doline v vasici Podbela, ki je od Kobarida oddaljena 11 kilometrov. V akciji Naj kamp Adria 2018 so kampisti izbrali kamp Nadiža kot tretji najboljši slovenski kamp v kategorij velikih kampov v Sloveniji.', '031888999', 'Stresova ulica 18, 5222 Kobarid', 'Kobarid', '46.242990', '13.457622', 7);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (11, 'Kamp Green Park', 'Kamp Green Park leži v kraju Žitomislići, 17 km južneje od Mostarja. Lokacija kampa je tik ob reki Neretvi in v bližini magistralne ceste, ki povezuje Mostar in Neum.', '041234234', 'Žitomislići bb, 88268 Mostar', 'Mostar', '43.200937', '17.796588', 8);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (12, 'Kamp Budva', 'Kamp Budva se nahaja v središču Budve in je od morja oz. Slovenske plaže oddaljen 500 m. Kamp ima cca 70 parcel, urejene sanitarije in dobro senco. Trgovina in restavracije so v neposredni bližini kampa.', '031963123', 'V ulica broj 1, Velji Vinograd', 'Budva', '42.286911', '18.845687', 9);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (13, 'Kamp Enigma', 'Kamp Enigma je nov kamp v južno Srbiji, ki je namenjen kampistom na poti proti Makedoniji in Grčiji. Leži 2,5 km od kraja Vranje in avtoceste Beograd - Skopje. Od Niša je kamp oddaljen 115 km, od srbsko - makedonske meje pa 45 km.', '051211777', 'Kupinince bb, 17500 Vranje', 'Vranje', '42.530977', '21.878494', 5);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (14, 'Kamp Pineta', 'Kamp Pineta Fažana se nahaja 2 km severno od Fažane, ki je od Pule oddaljena 5 km. Kamp ima urejene parcel v borovem gozdu, na travniku na levi strani kampa pa je neparceliran del, ki pa ima manj sence.  V kampu omogočajo tudi najem agencijskih mobilnih hišic Adriatic Kampovi', '041789987', 'Perojska cesta 41, 52212 Fažana', 'Fažana', '44.938806', '13.795504', 3);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (15, 'Camping Šobec', 'Kamp Šobec je že vrsto let uvrščen med najboljše kampe v Sloveniji. Razteza se v lepem borovem gozdu v bližini Lesc, med majhnim jezerom in reko Savo, z enkratnim pogledom na Julijske Alpe in Karavanke. Nahaja se samo 3 km od avtoceste Jesenice – Ljubljana, ob cesti, ki vodi od Lesc proti Bledu, ki je oddaljen le 3km.', '031444555', 'Šobčeva cesta 25, 4248 Lesce', 'Lesce', '46.353943', '14.148780', 6);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (2, 'Kamp Straško', 'Kamp Straško leži v kraju Novalja na otoku Pag. Kamp je urejen ob 2 km dolgi prodnati plaži. Je eden najbolj znanih hrvaških kampov in največji kamp na otoku Pagu. Celoten kamp Straško ima odlično senco hrastovih dreves, ki segajo vse do obale.', '013211232', 'Zeleni put 7, 53291 Novalja', 'Straško', '44.545390', '14.880870', 2);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (1, 'Kamp Njivice', 'Kamp Njivice je uvrščen med najboljše hrvaške kampe se nahaja ob morju obdan je s hrastovim gozdom, zaradi česar je v njem idealna senca na novo urejene parcele tudi do 120m2 elektrika in voda na vsaki parceli edinstvene mobilne hišice ob samem morju Cabana bar&more prelep lounge bar na plaži', '083211232', 'Morska ulica 113, 1000 Krk', 'Njivice', '45.180348', '14.545060', 1);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija)VALUES (4, 'Kamp Stella', 'Kamp Stella Maris Umag je bil v letu 2018 popolnoma prenovljen in je dobil novo recepcijo, novo urejene kamping parcele, bazen, restavracijo, ponudbo pa bodo dopolnili zmožnostjo najema modernih mobilnih hišic.', '041987789', 'Stella Maris 8a, 52470 Umag', 'Umag', '45.454242', '13.521910', 3);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (5, 'Kamp Zaton Holiday', 'Kamp Zaton je eden najboljših hrvaških kampov in se nahaja 16 km severno od Zadra oz. 1,5 km zahodno on kraja Nin. Gre za moderno urejen kamp z 1,5 km dolgo mivkasto in peščeno plažo. V kampu Zaton omogočajo kampiranje na urejenih parcelah, najem mobilnih hišic in glamping šotorov. V sklopu naselja omogočajo tudi najem številnih apartmajev.', '045123789', 'Dražnikova 76t, 23232 Nin', 'Nin', '44.222144', '15.171727', 2);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (6, 'Kamp Slanica', 'Kamp Slanica Murter se nahaja 2 km zahodno od kraja Murter, direktno ob plaži, ki pa je zelo raznolika. Del plaže je prodnat z mivko v vodi, del pa tudi skalnat. Iz kampa je prekrasen pogled na Kornate. V kampu Slanica omogočajo kampiranje na urejenih parcelah, najem mobilnih hišic in apartmajev.', '045897321', 'Podvrške 8, 22243 Murter', 'Murter', '43.817163', '15.576704', 2);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (17, 'KampTest2', 'Testni Kampic', '051897789', 'LALAL', 'Nekje', null, null, 1);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (16, 'KampTest', 'Testni Kampic', '051897789', 'LALAL', 'Nekje', null, null, 1);
INSERT INTO avtokampi (avtokamp_id, naziv, opis, telefon, naslov, naziv_lokacije, koordinata_x, koordinata_y, regija) VALUES (18, 'KampTest3', 'Testni Kampic', '051897789', 'LALAL', 'Nekje', null, null, 1);

INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (2, 'Posebni', 30, 1);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (1, 'Običajni', 21, 1);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (3, 'Osnovni', 51, 2);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (4, 'Osnovni', 82, 3);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (5, 'Posebni', 101, 4);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (6, 'Posebni', 67, 5);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (7, 'Posebni', 33, 6);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (8, 'Posebni', 23, 7);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (9, 'Posebni', 14, 8);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (10, 'Posebni', 26, 9);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (11, 'Posebni', 28, 10);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (12, 'Posebni', 39, 11);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (13, 'Posebni', 44, 12);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (14, 'Posebni', 45, 13);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (15, 'Posebni', 49, 14);
INSERT INTO ceniki (cenik_id, naziv, cena, avtokamp) VALUES (16, 'Posebni', 31, 15);

INSERT INTO kategorije (kategorija_id, naziv) VALUES (1, 'Osnovno');
INSERT INTO kategorije (kategorija_id, naziv) VALUES (2, 'Premium');
INSERT INTO kategorije (kategorija_id, naziv) VALUES (3, 'Luxury');

INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (1, 'IndijaKoromandija', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (2, 'Daleko', '200', 2, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (17, 'Ne tega zbrat', '100', 6, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (7, 'Kampirno mesto 5', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (19, 'Izjemen razgled', '100', 8, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (22, 'Super senčka', '100', 9, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (15, 'Tle so kače', '100', 5, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (10, 'Tle je super', '100', 3, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (18, 'Pazi se', '100', 7, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (25, 'Zvit teren', '100', 9, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (12, 'Kampirno mesto 12', '100', 4, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (26, 'Hude klopotače', '100', 10, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (14, 'Gud kampirno', '100', 5, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (4, 'Kampirno mesto 2', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (8, 'Zelo dobro mesto', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (23, 'Sonce nabija u glavo', '100', 9, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (16, 'Tle so pajki', '100', 5, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (21, 'Pouno dobrih ljudi', '100', 8, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (9, 'Varen pristan', '100', 2, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (6, 'Kampirno mesto 4', '100', 1, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (20, 'Babe so blizu', '100', 8, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (27, 'Povsod so babe', '100', 11, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (11, 'Izberi me', '100', 3, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (24, 'Ni elektrike', '100', 9, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (13, 'Kampirno mesto 13', '100', 4, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (32, 'Odlično mesto', '100', 1, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (43, 'Kampirno mesto 66', '100', 1, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (3, 'Raj kam drugam', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (36, 'Sončno mesto', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (39, 'Kampirno mesto 42', '100', 1, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (34, 'Sonce žge tle', '100', 1, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (5, 'Kampirno mesto 50', '100', 1, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (29, 'Lep bazenček', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (44, 'Kampirno mesto 88', '100', 15, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (31, 'Supersko mesto', '100', 12, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (30, 'Lepo mesto', '100', 11, 2);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (35, 'Senčno mesto', '100', 1, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (33, 'Izjemno mesto', '100', 10, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (37, 'Kampirno mesto 33', '100', 1, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (41, 'Kampirno mesto 102', '100', 13, 1);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (40, 'Kampirno mesto 405', '100', 13, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (42, 'Kampirno mesto 69', '100', 14, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (38, 'Kampirno mesto 44', '100', 1, 3);
INSERT INTO kampirna_mesta (kampirno_mesto_id, naziv, velikost, avtokamp, kategorija) VALUES (28, 'Ne me zbrat', '100', 11, 1);
